---
title: ''
output:
  word_document:
    reference_docx: style_for_RMD_thesis.docx
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(knitr.kable.NA = '')
```
# Разделение экологических ниш L. Saxatilis и L. Obtusata на территории Кандалакшского заповедника на острове Ряжков

# Бритиков А.И.1, Хайтов В.М.󠆺123*
## 1.Лаборатория экологии морского бентоса (гидробиологии), ЭБЦ «Крестовский остров». Санкт-Петербург
## 2.Санкт-Петербургский государственный университет, кафедра зоологии беспозвоночных, Санкт-Петербург 
## 3.Кандалакшский государственный заповедник, Кандалакша
## *E-mail: polydora@rambler.ru

&nbsp;

Экологическая ниша - это гиперобъем различных экологических факторов в пространстве в пределах которого вид может жить. Такими факторами могут быть температура, влажность или соленость (@schoener1989ecological). Среди близкородственных видов, ввиду схожести их ниш, наблюдается их разделение. Так появляется ниша потенциальная, в которой организм может существовать при приемлемых факторах, и реализованная ниша, в которой организм существует из-за конкуренции с другим видом, не позволяющим ему занять свою нишу полностью. Подобная картина достаточно хорошо видна у двух видов литторин, у L. Saxatilis и L. Obtusata, чье разделение ниш мы попытались изучить.

Работа проводилась на территории Кандалакшского заповедника на острове Ряжков. Непосредственный сбор материалов происходил на илисто-песчаной литорали Южной губы и на литорали около скальных выходов. Было установлено две трансекты, по одной на каждую литораль. На южногубской литорали трансекта состояла из двенадцати уровней с промежутком в пять метров. На каждом уровне собирались все улитки находящиеся в трех случайно расположенных рамках 1/40 квадратного метра. На трансекте около скальных выступов было девять уровней с промежутками в десять метров, кроме трех верхних, расстояние между которыми было пять метров. Там на каждом уровне мы брали по пять аналогичных рамок. У собранных моллюсков мы определяли вид. Высоту между уровнями мы измеряли с помощью водяного уровня. В ходе отдельного эксперимента мы брали моллюсков двух видов и помещали их в индивидуальную ячейку с водой на сутки, чтобы подсчитать число выделившихся пеллет, а за тем измерить их. Этих улиток мы помещали в садки содержащие фукоиды или камни на сутки в морскую воду, чтобы потом поместить их в ячейки и посчитать число выделившихся пеллет у голодных улиток.

Полученные нами данные показали, что L. Obtusata чаше встречается на более низких участках литорали ближе к поясу фукоидов, а L. Saxatilis чаще встречаются на более высоких участках литорали.

В ходе эксперимента было выявлено, что L. Obtusata выделяет пеллет больше на фукоидном субстрате, чем на каменистом, в отличие от L. Saxatilis выделявших пеллет больше на камнях. Это позволяет предположить, что в данном случае мы можем наблюдать фундаментальное разделение экологических ниш.

# Separation of the ecological niches of L. Saxatilis and L. Obtusata on the territory of the Kandalaksha Reserve on Ryazhkov Island

# Britikov A.1, Khaitov V.123*
## 1.Laboratory of Marine Benthic Ecology, “Krestovsky ostrov” Ecology and Biology centrum, Saint Petersburg 
## 2.Saint Petersburg University, Department of Invertebrate Zoology, Saint Petersburg 
## 3.Kandalaksha State Nature Reserve, Kandalaksha 
## *E-mail: polydora@rambler.ru 

&nbsp;

An ecological niche is a hypervolume of environmental factors in which a species can live. There is a potential niche where an organism can exist and a realized niche where it competes with another species. Studies on L. saxatilis and L. obtusata in Kandalaksha reserve showed that L. obtusata is more common at lower levels of the littoral and L. saxatilis at upper levels. The experiment revealed that species excrete different amounts of feces on different substrates, confirming the separation of ecosystem niches.





