---
title: ''
output:
  word_document:
    reference_docx: style_for_RMD_thesis.docx
bibliography: bibliography.bib
---

```{r setup, include=FALSE}

library(knitr)

# citation of kozminsky2013 and berry 1961 rewrite
# library(csl)
# install.packages("csl")

opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(knitr.kable.NA = '')
```

# Разделение каких экологических ниш Littorina saxatilis и L. obtusata мы наблюдаем на литоррали Белого моря?

&nbsp;

### Бритиков А.И.1, Хайтов В.М.󠆺123*

## 1.Лаборатория экологии морского бентоса (гидробиологии), ЭБЦ «Крестовский остров». Санкт-Петербург
## 2.Санкт-Петербургский государственный университет, кафедра зоологии беспозвоночных, Санкт-Петербург 
## 3.Кандалакшский государственный заповедник, Кандалакша
## *E-mail: alexbritik@gmail.com

&nbsp;

Два вида улиток, самых многочисленных для литорали северной Атлантики, L. saxatilis (далее Ls) и L. obtusata (Lo), закономерно распределены по разным горизонтам осушки: Lo поселяются на нижних уровнях, тяготея к фукоидам (@kozminsky2013effects), а Ls обильны на более высоких уровнях (@berry1961some). Для оценки распределения Ls и Lo на литорали Белого моря мы провели оценку их обилия на разных высотах относительно нуля глубин. На двух участках илисто-песчаной литорали были заложены трансекты, проложенные от уреза воды во время отлива до верхней границы литорали. На нескольких уровнях осушки собирали всех улиток с нескольких площадок известной площади. Высоту между уровнями относительно нуля глубин измеряли с помощью водяного уровня. Было показано, что Lo демонстрирует пик плотности в нижних частях трансект, соответствующих поясу фукоидов. Второй вид (Ls) имел пик обилия выше по литорали, где представлены в основном камни или скальные выходы. Этот паттерн можно объяснить действиями двух механизмов. Во-первых, пространственная сегрегация может быть следствием конкурентных отношений, а наблюдаемая картина демонстрирует расхождение реализованных экологически ниш. Во-вторых, наблюдаемое расхождение может быть следствием различия фундаментальных ниш двух видов: моллюски распределяются по тем частям градиента условий, которые соответствуют их видоспецифическим чертам.

Для выбора между этими альтернативами мы провели эксперименты. Улиток двух видов выдерживали в течение суток без еды, чтобы они очистили кишечник от остатков пищи. После этого животных помещали в садки, содержащие либо камни, собранные с литорали, либо фукоиды. После 24 часов экспозиции в садках с этими субстратами улиток рассаживали в индивидуальные ячейки с водой на одни сутки. После этого подсчитывали число пеллет фекалий, которые вышли из кишечника. В результате было показано, что Ls выделяет больше фекалий, если находились в садках с камнями, чем при содержании в садках с фукоидами. Это можно трактовать, как следствие более интенсивного питания, происходившего на камнях. В случае с Lo наблюдалась обратная картина - улитки более интенсивно выделяли пеллеты, а стало быть и питались, в садках с фукоидами. Полученные данные говорят о том, что более интенсивное питание происходило на тех субстратах, которые доминировали на тех уровнях литорали, где наблюдались пики численности видов. Этот результат свидетельствует в пользу того, что вертикальный паттерн распределения литторин является следствием разделения фундаментальных ниш моллюсков.


# Separation of the ecological niches of L. Saxatilis and L. Obtusata on the territory of the Kandalaksha Reserve on Ryazhkov Island

### Britikov A.1, Khaitov V.123*
## 1.Laboratory of Marine Benthic Ecology, “Krestovsky ostrov” Ecology and Biology centrum, Saint Petersburg 
## 2.Saint Petersburg University, Department of Invertebrate Zoology, Saint Petersburg 
## 3.Kandalaksha State Nature Reserve, Kandalaksha 
## *E-mail: polydora@rambler.ru 

&nbsp;

Two transects were laid in the White Sea littoral to estimate the abundance of L. obtusata and L. saxatilis at different littoral horizons. We experimentally discovered that snails feed more actively on those substrates that are present in the biotopes where they are most abundant.



